<a href="https://colab.research.google.com/github/anshuldaksh2016/pytorch-work/blob/master/Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import torch as torch

In [2]:
torch.__version__

'1.5.1+cu101'

In [1]:
import numpy as np

In [2]:
lst = [2,4,5,6,8]

In [3]:
arr = np.array(lst)

In [5]:
arr.dtype

dtype('int64')

In [6]:
type(arr)

numpy.ndarray

##COnvert Numpy to pytorch tensors 

In [15]:
tensors = torch.from_numpy(arr)
tensors , tensors.dtype

(tensor([2, 4, 5, 6, 8]), torch.int64)

In [10]:
arr.ndim

1

In [12]:
id(tensors) , id(arr)

(140124991460624, 140126220200816)

In [16]:
tensors[:2]

tensor([2, 4])

In [17]:
tensors[:]

tensor([2, 4, 5, 6, 8])

In [18]:
tensors[:-1]

tensor([2, 4, 5, 6])

In [19]:
tensors[1:4]

tensor([4, 5, 6])

In [20]:
tensors[-1:]

tensor([8])

In [21]:
tensors

tensor([2, 4, 5, 6, 8])

In [22]:
tensors[3] = 500

In [23]:
tensors

tensor([  2,   4,   5, 500,   8])

In [24]:
arr

array([  2,   4,   5, 500,   8])

In [26]:
# prevvent this by using torch.tensor
tensor_arr = torch.tensor(arr)

In [27]:
tensor_arr

tensor([  2,   4,   5, 500,   8])

In [28]:
tensor_arr[2] = 200

In [29]:
arr

array([  2,   4,   5, 500,   8])

In [30]:
print(tensor_arr)
print(arr)

tensor([  2,   4, 200, 500,   8])
[  2   4   5 500   8]


In [9]:
# zeros and ones 
print(torch.zeros(2,3 , dtype=torch.int64) )

print(torch.ones(3,4 , dtype=torch.float32))

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Arithmetic Operations 

In [41]:
 a = torch.tensor([3,4,5] , dtype = torch.float)
 b = torch.tensor([6,7,8], dtype = torch.float )

In [12]:
a , b

(tensor([3., 4., 5.]), tensor([6., 7., 8.]))

In [18]:
print(a + b)

tensor([ 9., 11., 13.])


In [21]:
c = torch.zeros(4 , 3)

In [22]:
c

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [25]:
import numpy as np
a = torch.tensor(np.arange(0,15).reshape(5,3))

In [29]:
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [33]:
a[0:1]

tensor([[0, 1, 2]])

In [38]:
a[:,2]

tensor([ 2,  5,  8, 11, 14])

In [39]:
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [42]:
torch.add(a,b ,out = c)

tensor([ 9., 11., 13.])

In [43]:
c

tensor([ 9., 11., 13.])

In [44]:
torch.add(a,b).sum()

tensor(33.)

Dot products and multiplication


In [46]:
a.mul(b)

tensor([18., 28., 40.])

In [47]:
a.dot(b)

tensor(86.)

In [48]:
# Matrix multiplication

In [52]:
x = torch.tensor([[1,4,2],[1,5,5]] , dtype=torch.float)
y = torch.tensor([[5,7],[8,7],[9,11]] ,dtype = torch.float)

In [53]:
torch.matmul(x,y)

tensor([[55., 57.],
        [90., 97.]])